// import  SellersHomePage from './pos/home/page'
import type { Metadata } from "next";
// import localFont from "next/font/local";

import PosWrapper from "./pos/pos-wrapper";
// import Dashboardwrapper from "@/app/dashboardwrapper";
import AuthProvider from "@/app/context/authProvider";

// import Home from "./page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SellerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <PosWrapper>{children}</PosWrapper>
          {/* <Home> {children} </Home>  */}
          {/* <Dashboardwrapper>{children}</Dashboardwrapper> */}
          {/* <SellersHomePage>{children}</SellersHomePage> */}
        </AuthProvider>
      </body>
    </html>
  );
}
