// import  SellersHomePage from './pos/home/page'
import type { Metadata } from "next";
import "./globals.css";
// import localFont from "next/font/local";

import PosWrapper from "./pos/pos-wrapper";
// import Dashboardwrapper from "@/app/dashboardwrapper";
import AuthProvider from "@/app/context/authProvider";
import Head from 'next/head';

// import Home from "./page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SellerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {/* You can also add other meta tags, title, etc. */}
        <title>Your App Title</title>
      </Head>
      <body>
        <AuthProvider>
          <PosWrapper>{children}</PosWrapper>
          {/* <Home> {children} </Home>  */}
          {/* <Dashboardwrapper>{children}</Dashboardwrapper> */}
          {/* <SellersHomePage>{children}</SellersHomePage> */}
        </AuthProvider>
      </body>
    </html>
  );
}
