name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch
    paths:
      - 'backend/**'  # Only trigger if files in the backend folder are changed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set the Node.js version required for the backend

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run ESLint check
        working-directory: ./backend
        run: npm run lint:check  # Lint the backend code

      - name: Run Prettier check
        working-directory: ./backend
        run: npm run prettier:check  # Prettier check

  build_and_migrate:
    runs-on: ubuntu-latest
    needs: lint  # Ensure linting happens before build & migration

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Build project
        working-directory: ./backend
        run: npm run build  # Build the backend code

      - name: Run Database Migrations (Production)
        working-directory: ./backend
        run: npm run migrate:prod  # Run production migrations using Prisma

      - name: Generate Documentation (optional)
        working-directory: ./backend
        run: npm run generate-docs  # Optional: Generate docs if needed

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_migrate  # Deploy after build and migrations

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: build
        run : npm run build

      - name: run build
        run: echo "Deploying..."
            
