name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - deployment-setup  # Trigger deployment on changes to the main branch
    paths:
      - 'frontend/**'  # Only trigger if files in the frontend folder are changed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: starting runnig build
        run : echo 'running'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Set the Node.js version required for the project

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Next.js app
        working-directory: ./frontend
        run: npm run build

      - name: runni build
        run : echo 'finished building'

      # - name: Deploy to Vercel
      #   working-directory: ./frontend
      #   run: vercel --prod --token ${{ secrets.VERCEL_TOKEN }}  # Use Vercel token from secrets
